### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by der-ede** [yldio/react-native-offline-first#3]
Hi there,

when building as described in this repos read I get:

```
/Users/.../react-native-offline-first/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:154
      throw err;
      ^

SyntaxError: /Users/.../package.json: Error while parsing JSON - Unexpected token /
    at Object.parse (native)
    at ConfigChainBuilder.addConfig (/Users/.../react-native-offline-first/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:150:65)
    at ConfigChainBuilder.findConfigs (/Users/.../react-native-offline-first/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:102:30)
    at buildConfigChain (/Users/.../react-native-offline-first/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
    at OptionManager.init (/Users/.../react-native-offline-first/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at compile (/Users/.../react-native-offline-first/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/.../react-native-offline-first/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/.../react-native-offline-first/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by der-ede** [comment]
Updating package.json to 
```
{
  "name": "ReactNativeOffline",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "lodash.find": "4.4.0",
    "pouchdb-react-native": "^5.4.9",
    "react": "15.4.2",
    "react-native": "0.41.0"
  }
}
```
works but gives other errors.

**Comment by jgalmeida** [comment]
Hi @der-ede,

Could you have a look at this regarding xcode 8, https://github.com/yldio/react-native-offline-first/issues/2#issuecomment-272152783.

Thanks

**Comment by der-ede** [comment]
Hi @Joao:

The problem could be solved by installing the example in the example folder of your repo pouchdb-react-native as this is more recent. Maybe you could put a link in the readme of this repo.
Also react-native, npm, node etc. need to be updated to the newest version.

Regards
